[package]
name = "rusty_wiki_front"
version = "0.1.0"
authors = ["yoshitsugu <yoshitsugu@users.noreply.github.com>"]

[dependencies]
stdweb = "0.4.2"
yew = "0.3.0"
yew_simple = "0.1.0"
failure = "0.1.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"