version: '3'

volumes:
  wiki-db:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - wiki-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pgpass
  h2o:
    image: lkwg82/h2o-http2-server
    ports:
      - "8083:80"
    volumes:
      - ./containers/dev/h2o:/etc/h2o